In [20]:
import pandas as pd
import numpy as np
import re

In [118]:
df = pd.read_csv('dataset/globalterrorismdb_modified.csv')
df.columns

Index(['Unnamed: 0', 'eventid', 'iyear', 'imonth', 'iday', 'country_txt',
       'region_txt', 'provstate', 'city', 'latitude', 'longitude', 'success',
       'attacktype1_txt', 'targtype1_txt', 'gname', 'weaptype1_txt'],
      dtype='object')

In [113]:
for column in df:
        if column.startswith('i'):
            column = column.replace('i', '')
            print(column)

year
month
day

In [122]:
def rename_column(df):
    '''
    MODIFICAR EL NOMBRE DE LAS COLUMNAS QUE EMPIECEN EN 'i' PARA ELIMINAR ESTA PARTE
    :return: el DataFrame con las columnas limpias
    '''
    for column in df:
        if column.startswith('i'):
            new = column.replace('i', '')
            df[new] = df[column]
        if column.endswith('1_txt'):
            new = column.replace('1_txt', '')
            df[new] = df[column]
        if column.endswith('_txt'):
            new = column.replace('_txt', '')
            df[new] = df[column]
    print('RENOMBRAR iCOLUMNAS  ----- EXITO' + '\n')
    return df

In [123]:

rename_column(df)
df.head()

RENOMBRAR iCOLUMNAS  ----- EXITO

,Unnamed: 0,eventid,iyear,imonth,iday,country_txt,region_txt,provstate,city,latitude,...,month,day,country,region,attacktype1,targtype1,weaptype1,attacktype,targtype,weaptype
0,0,197000000001,1970,7,2,Dominican Republic,Central America & Caribbean,NaN,Santo Domingo,18.456792,...,7,2,Dominican Republic,Central America & Caribbean,Assassination,Private Citizens & Property,Unknown,Assassination,Private Citizens & Property,Unknown
1,1,197000000002,1970,0,0,Mexico,North America,Federal,Mexico city,19.371887,...,0,0,Mexico,North America,Hostage Taking (Kidnapping),Government (Diplomatic),Unknown,Hostage Taking (Kidnapping),Government (Diplomatic),Unknown
2,2,197001000001,1970,1,0,Philippines,Southeast Asia,Tarlac,Unknown,15.478598,...,1,0,Philippines,Southeast Asia,Assassination,Journalists & Media,Unknown,Assassination,Journalists & Media,Unknown
3,3,197001000002,1970,1,0,Greece,Western Europe,Attica,Athens,37.997490,...,1,0,Greece,Western Europe,Bombing/Explosion,Government (Diplomatic),Explosives,Bombing/Explosion,Government (Diplomatic),Explosives
4,4,197001000003,1970,1,0,Japan,East Asia,Fukouka,Fukouka,33.580412,...,1,0,Japan,East Asia,Facility/Infrastructure Attack,Government (Diplomatic),Incendiary,Facility/Infrastructure Attack,Government (Diplomatic),Incendiary